In [12]:
import json
import pandas as pd
import numpy as np

In [13]:
file_name = './active_hits-v1-argumentative-res-2379498895443566127.json'

In [14]:
with open(file_name, 'r') as fout:
    results = json.load(fout)
df = pd.read_csv('active_hits_tweets.csv')

In [15]:
dist = {}
for item in results:
    key = item['assignments_submitted_count']
    if key in dist:
        dist[key] = dist[key] + 1
    else:
        dist[key] = 1
        
dist

{5: 528, 4: 71, 3: 1}

In [16]:
arguments = []
for item in results:
    answers = item['answers']
    tweet = item['tweet']
    arg_dist = {}
    for answer in answers:
        key = answer['QuestionFormAnswers']['Answer']['FreeText'] 
        if key in arg_dist:
            arg_dist[key] = arg_dist[key] + 1
        else:
            arg_dist[key] = 1
    
    super_majority = max(list(arg_dist.values())) > 3
    arguments.append((tweet, arg_dist, super_majority))

In [17]:
super_majors = 0

for (_, _, sup) in arguments:
    super_majors = super_majors + sup
super_majors

274

In [18]:
for (tweet, arg_dist, sup) in arguments:
    row = df[df.tweet == tweet]
    df.loc[df.tweet == tweet, 'argumentative'] = (arg_dist['argumentative'] if 'argumentative' in arg_dist else 0)/sum(arg_dist.values())

In [19]:
df#[df.argumentative > .49]

,Unnamed: 0,Unnamed: 0.1,index,tweet,id,lang,score,evidence,claim,procon,arg_type,evidence_type,topic,argumentative
0,661,661.0,15434,<MENTION> <MENTION> I thought due to more clim...,1.511334e+18,en,0.646619,0.0,0.0,0.0,NaN,NaN,NaN,0.4
1,107,NaN,32186,It’s better than Whole Foods imo &amp; y’all k...,1.511776e+18,en,0.000000,0.0,0.0,0.0,NaN,NaN,Meat alternatives should be subsidized,0.4
2,314,314.0,18711,<MENTION> <MENTION> She seem to be working 16h...,1.512011e+18,en,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,0.25
3,277,277.0,13270,Just tried Burger King's plant-based burgers. ...,1.512000e+18,en,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,0.4
4,478,478.0,25604,#WorldHealthDay \nUnder the guidance of revere...,1.511901e+18,en,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,67,67.0,29601,<MENTION> <MENTION> <MENTION> When top athlete...,1.511461e+18,en,0.650733,0.0,0.0,0.0,NaN,NaN,NaN,0.6
596,699,699.0,27833,Grandparents are so cute. Went to my mom and d...,1.511902e+18,en,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,0.4
597,783,783.0,6434,<MENTION> <MENTION> Obviously - which is why I...,1.510560e+18,en,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,0.8
598,716,716.0,17409,<MENTION> Once the story disappears in the fog...,1.510947e+18,en,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,0.4
599,180,NaN,49,<MENTION> <MENTION> Look at those nutrition gu...,1.510573e+18,en,0.646790,0.0,0.0,0.0,NaN,NaN,We should subsidize green nutrition,0.6

In [11]:
df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1']).to_csv('argumentative.csv')